### ISSUE TITLE
Issues if 00:00 or 12:00 AM

### ISSUE THREAD

**Issue by 123445666** [jonthornton/jquery-timepicker#742] opened 2020-11-19 12:36 UTC
When input 00:00 or 12:00 AM. It's changing value to 0

**Comment by 123445666** [comment] 2020-11-19 12:37
the issue of the version 1.13.15.

**Comment by jonthornton** [comment] 2020-12-07 03:48
This should be fixed in 1.13.16

**Closed by jonthornton** 2020-12-07 03:48 UTC

**Comment by bulauza** [comment] 2021-01-26 12:10
I use ver1.13.16，but I seem to be experiencing the same problem.

**Comment by jonthornton** [comment] 2021-02-06 22:19
@bulauza I'm unable to reproduce the error myself. Can you post a jsfiddle and instructions that demonstrate the error?

**Comment by bulauza** [comment] 2021-02-07 06:25
@jonthornton 
When select 00:00, this issue will happen.
jsfiddle is [here](https://jsfiddle.net/yxg270ma/).

**Comment by jonthornton** [comment] 2021-02-07 19:08
@bulauza thank you! Try https://github.com/jonthornton/jquery-timepicker/releases/tag/1.13.17

**Comment by bulauza** [comment] 2021-02-07 19:26
@jonthornton LGTM. Thank you!
