### ISSUE TITLE
Overlapping time ranges over those disabled

### ISSUE THREAD

**Issue by andriuhatm** [jonthornton/jquery-timepicker#412] opened 2015-07-13 07:50 UTC
For example, if i have defaultTimeDelta set to 3 hours and i choose a start time before the disabled period, the end time goes over the disabled period.

Example: 
'disableTimeRanges': [ [ 8:00, 9:00 ], [ 11:00, 13:00 ] ]

I don't have to be able to select 10:00 because the timeDelta is 3 hours. How to disable 3 hour period before second time range?
And there might be more keys in array, because the disabled time period is returned from Google Calendar API..
Thx..

**Comment by jonthornton** [comment] 2015-07-26 23:55
Duplicate of https://github.com/jonthornton/Datepair.js/issues/45

**Closed by jonthornton** 2015-07-26 23:55 UTC
