### ISSUE TITLE
Chrome bug - Duplicated timings

### ISSUE THREAD

**Issue by mikeholford** [jonthornton/jquery-timepicker#479] opened 2016-02-02 01:15 UTC
I thought I was going mad but from the downloaded zip: Opening up index in chrome causes a duplicate "10:00" and "10:30" entry. I tested in Safari and this is not the case. See pictures below:

**CHROME**
<img width="1437" alt="screen shot 2016-02-02 at 12 04 42" src="https://cloud.githubusercontent.com/assets/5775030/12736687/99897db2-c9a6-11e5-9571-0a55052d88d7.png">

**SAFARI**
<img width="1439" alt="screen shot 2016-02-02 at 12 05 04" src="https://cloud.githubusercontent.com/assets/5775030/12736688/9b2968b2-c9a6-11e5-8348-d2445ee2681a.png">

**Comment by jonthornton** [comment] 2016-02-02 01:24
I'm unable to reproduce this with Chrome 47.0.2526.111 on OS X :/

Any ideas?

![screen shot 2016-02-01 at 8 23 40 pm](https://cloud.githubusercontent.com/assets/196831/12736835/b6bdca8a-c921-11e5-9710-02952139deef.png)

**Comment by karin-n** [comment] 2016-03-11 02:36
I have got the same issue, although in my case the 12pm and 12:30pm values are duplicated. 
Chrome version 48.0.2564.116 on OS X 10.11.3

<img width="581" alt="screenshot 2016-03-11 15 33 33" src="https://cloud.githubusercontent.com/assets/1925851/13691564/c6894ac0-e79e-11e5-8dfc-617d956d977e.png">

**Comment by jonthornton** [comment] 2016-04-18 01:50
This may have been fixed by https://github.com/jonthornton/jquery-timepicker/commit/2fcde1617e5e2581eb945516293013d5ad7a0da7. Can you confirm?

**Closed** 2016-05-22 18:07 UTC
Labels: notconfirmed
