### ISSUE TITLE
Timepicker is shown on focus even if empty showOn option

### ISSUE THREAD

**Issue by sanada-sra** [jonthornton/jquery-timepicker#671] opened 2018-06-25 11:18 UTC
To disable showing timepicker on focus, some options are set.

First time, Timepicker is not shown on focus.
But, once after timepicker is shown on click button and time is selected, Timepikcer is shown on focus.

I use timepicker with following options in order to hide timepicker on focus.
 * showOn : empty
 * showOnFocus : false
and instead of above, I set event handler to button click.

**Sample code**
```javascript
    $("#i1").timepicker({showOn:[], showOnFocus:false});
    $("button").on("click", function() {
        $("#i1").timepicker("show");
    });
```

**Steps to reproduce**
1. click button and timepicker is shown.
2. select time.
3. focus textbox. (timepicker is shown!?)

I gess that the function 'render' should be check whether showOn options has focus.

**Comment by jonthornton** [comment] 2022-10-01 20:43
This appears to be fixed in the latest version; I'm unable to reproduce it.

**Closed by jonthornton** 2022-10-01 20:43 UTC
