### ISSUE TITLE
timepicker not hiding on window resize

### ISSUE THREAD

**Issue by arpad9** [jonthornton/jquery-timepicker#355] opened 2015-02-12 22:49 UTC
v1.6.0
Browsers: FF35, Chrome40, PhantomJS (testing)
O/S: Ubuntu 14.10

Had to do this to get it to work:
```coffeescript
  $('.timepicker input').on 'showTimepicker', ->
    $(window).on 'resize', ->
      $('.timepicker input').timepicker('hide')

  $('.timepicker input').on 'hideTimepicker', ->
    $(window).unbind('resize')
```
I see that this was an issue a few years back.  Maybe I'm missing something?

**Comment by jonthornton** [comment] 2015-02-18 00:33
> I see that this was an issue a few years back

I don't recall ever addressing window resize. The current intended behavior is for nothing to happen - if the timepicker is open when a user initiates a resize, the timepicker stays open. Is there a reason to change this?

**Comment by andreyvolokitin** [comment] 2015-02-23 19:52
When browser window is resized, position of timepicker input may be changed. But position of the opened timepicker - does not. So, it would be convinient either to reposition timepicker according to the new input position on window resize, or close it.

**Closed** 2015-03-08 19:03 UTC
Labels: enhancement
